import type * as NodeModule from 'node:module'
import { describe, expect, it, vi } from 'vitest'
import type { MigrationPlan } from '../packages/better-newsletter/src/db/migration.js'
import { runBetterNewsletterCli } from '../packages/cli/src/cli/run.js'

const cliResolution = vi.hoisted(() => ({
  runtimeVersion: '0.1.0-beta.99',
  require: vi.fn(() => ({ version: '0.1.0-beta.99' }))
}))

// Simulate the runtime dependency seen from a different CLI installation.
vi.mock('node:module', async importOriginal => ({
  ...await importOriginal<typeof NodeModule>(),
  createRequire: () => cliResolution.require
}))

vi.mock('../packages/cli/src/migration/config-loader.js', () => ({
  loadMigrationConfig: async () => ({
    config: {
      provider: {
        dialect: 'postgres',
        plan: async (): Promise<MigrationPlan> => ({
          dialect: 'postgres', targetRevision: 1, kind: 'initial',
          runtimeVersion: '0.1.0-beta.7', namespace: 'public',
          toBeCreated: ['newsletter_fixture'], toBeAdded: [],
          statements: ['CREATE TABLE newsletter_fixture (id text)'],
          sql: 'CREATE TABLE newsletter_fixture (id text);\n', isCurrent: false
        }),
        apply: async () => { throw new Error('Generate must not apply migrations') }
      }
    }
  })
}))

describe('CLI/runtime provenance mismatch', () => {
  it('preserves the provider version instead of resolving a different CLI-local runtime', async () => {
    const writeFile = vi.fn()
    const stderr = vi.fn()
    expect(await runBetterNewsletterCli(['generate', '--yes'], {
      cwd: () => '/host', stdout: vi.fn(), stderr,
      isInteractive: () => false, confirm: async () => false,
      exists: () => false, writeFile
    })).toBe(0)
    expect(stderr).not.toHaveBeenCalled()
    const generated: string = writeFile.mock.calls[0]![1]
    expect(generated).toContain('-- Generated by better-newsletter@0.1.0-beta.7\n')
    expect(generated).not.toContain(cliResolution.runtimeVersion)
    expect(cliResolution.require).not.toHaveBeenCalled()
  })
})
