export interface MigrationPlan {
  readonly dialect: string
  /** Installed provider's schema target, not an observed or persisted database revision. */
  readonly targetRevision: number
  /** Whether inspection found an effectively empty or existing newsletter target. */
  readonly kind: 'initial' | 'delta'
  /** Runtime package version that owns this schema target. */
  readonly runtimeVersion: string
  readonly namespace: string
  readonly toBeCreated: readonly string[]
  readonly toBeAdded: readonly string[]
  readonly statements: readonly string[]
  readonly sql: string
  readonly isCurrent: boolean
}

export interface MigrationProvider {
  readonly dialect: string
  plan(): Promise<MigrationPlan>
  apply(plan: MigrationPlan): Promise<void>
}

export interface BetterNewsletterMigrationConfig {
  readonly provider: MigrationProvider
  /**
   * Optional host-owned cleanup for CLI usage, for example `db.destroy()`.
   * The provider never destroys a host database connection implicitly.
   */
  readonly close?: () => void | Promise<void>
}

export interface NewsletterMigrations extends MigrationPlan {
  runMigrations(): Promise<void>
}

export function defineBetterNewsletterMigrationConfig<
  T extends BetterNewsletterMigrationConfig
>(config: T): T {
  return config
}

export async function getMigrations(
  config: BetterNewsletterMigrationConfig
): Promise<NewsletterMigrations> {
  const plan = await config.provider.plan()
  return {
    ...plan,
    async runMigrations() {
      if (plan.isCurrent) return
      await config.provider.apply(plan)
    }
  }
}

/** Adds deterministic provenance for a static, host-owned migration file. */
export function renderMigrationSql(
  plan: Pick<MigrationPlan, 'dialect' | 'targetRevision' | 'kind' | 'runtimeVersion' | 'sql'>
): string {
  return [
    `-- Generated by better-newsletter@${plan.runtimeVersion}`,
    `-- Dialect: ${plan.dialect}`,
    `-- Target schema revision: ${plan.targetRevision}`,
    `-- Plan: ${plan.kind}`,
    '',
    plan.sql
  ].join('\n')
}
